"""Domain models for the Spatial Decision Intelligence engine.

v1.0 aligned: Beijing Residential Ontology Profile.
"""

from src.domain.contracts import (
    AssertionType,
    AuthorityAssertion,
    BenchmarkRunRecord,
    BoundaryHypothesis,
    BoundaryRepresentation,
    BoundaryType,
    BoundaryUncertaintyZone,
    BuildingFunction,
    BuildingMembershipState,
    ConnectorFeature,
    ConnectorType,
    ErrorAttribution,
    Evidence,
    EvidenceSufficiency,
    EvidenceType,
    GoldAdjudication,
    GoldCorrectionRecord,
    GoldState,
    HypothesisStatus,
    MorphologyType,
    Observation,
    OntologyType,
    ProviderResult,
    ProviderStatus,
    RelationMeasurement,
    RelationType,
    RepresentationOrigin,
    RoadRole,
    SeparatorFeature,
    SeparatorType,
    SpatialEntity,
    SpatialRelation,
    SpatialRepresentation,
    TrustedSpatialState,
    ValidationResult,
    ValidationStatus,
)
from src.domain.ontology import is_valid_ontology_type, ontology_type_from_name

__all__ = [
    "AssertionType",
    "AuthorityAssertion",
    "BenchmarkRunRecord",
    "BoundaryHypothesis",
    "BoundaryRepresentation",
    "BoundaryType",
    "BoundaryUncertaintyZone",
    "BuildingFunction",
    "BuildingMembershipState",
    "ConnectorFeature",
    "ConnectorType",
    "ErrorAttribution",
    "Evidence",
    "EvidenceSufficiency",
    "EvidenceType",
    "GoldAdjudication",
    "GoldCorrectionRecord",
    "GoldState",
    "HypothesisStatus",
    "MorphologyType",
    "Observation",
    "OntologyType",
    "ProviderResult",
    "ProviderStatus",
    "RelationMeasurement",
    "RelationType",
    "RepresentationOrigin",
    "RoadRole",
    "SeparatorFeature",
    "SeparatorType",
    "SpatialEntity",
    "SpatialRelation",
    "SpatialRepresentation",
    "TrustedSpatialState",
    "ValidationResult",
    "ValidationStatus",
    "is_valid_ontology_type",
    "ontology_type_from_name",
]